apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus
    app.kubernetes.io/part-of: stephanie-app
  name: inventory-quarkus
  namespace: yangcao
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: inventory-quarkus
    weight: 100
status: {}
